const data = {
  romantik: [
"❤️ Beni ilk gördüğünde aklından ne geçti?",
"❤️ Benim hangi özelliğim seni bana bağladı?",
"❤️ Benimle tanıştığın günü tekrar yaşamak ister miydin?",
"❤️ Birlikte geçirdiğimiz en güzel gün hangisiydi?",
"❤️ Sana kendini en özel hissettirdiğim an neydi?",
"❤️ Benim için yazacağın bir aşk cümlesi ne olurdu?",
"❤️ İlişkimiz bir film olsaydı adı ne olurdu?",
"❤️ Benimle ilgili ilk fark ettiğin şey neydi?",
"❤️ Seni en çok hangi davranışımla mutlu ediyorum?",
"❤️ Benim yanımda kendini nasıl hissediyorsun?",
"❤️ Beni üç kelimeyle nasıl anlatırsın?",
"❤️ Birlikte yaşlanmayı hayal ediyor musun?",
"❤️ Benimle ilgili unutamadığın an hangisi?",
"❤️ Sana göre aşkımızın en güzel tarafı ne?",
"❤️ Beni özlediğinde ilk ne yapmak istersin?",
"❤️ İlk sarıldığımız anı hatırlıyor musun?",
"❤️ Benim sesimde en sevdiğin şey ne?",
"❤️ Birlikte gitmek istediğin yer neresi?",
"❤️ Gelecekte bizim için kurduğun en güzel hayal ne?",
"❤️ Benim hangi huyum seni güldürüyor?",
"❤️ Sana göre ilişkimizin en güçlü yanı ne?",
"❤️ Birlikte yapmak istediğin şey nedir?",
"❤️ Benimle ilgili en çok neyi seviyorsun?",
"❤️ Benim gözlerime baktığında ne hissediyorsun?",
"❤️ Hayatında benim yerim nasıl bir yerde?",
"❤️ Benimle ilgili seni şaşırtan şey neydi?",
"❤️ Sana göre en romantik anımız hangisi?",
"❤️ Bana söylemek isteyip söyleyemediğin bir şey var mı?",
"❤️ Birlikte yaşayacağımız en güzel an ne olabilir?",
"❤️ Benim için bir şarkı seçsen hangisi olurdu?",
"❤️ İlk mesajımızı hatırlıyor musun?",
"❤️ Benimle ilgili ilk izlenimin neydi?",
"❤️ Bir günlüğüne zamanı durdursak ne yapardık?",
"❤️ Benim yanımda en mutlu olduğun an hangisi?",
"❤️ Beni neden hayatında istiyorsun?",
"❤️ Birlikte kurduğun en çılgın hayal ne?",
"❤️ Bana olan sevgini tek cümleyle anlatır mısın?",
"❤️ Benimle ilgili en değer verdiğin şey ne?",
"❤️ İlişkimizin en güzel sürprizi neydi?",
"❤️ Beni en çok ne zaman özlüyorsun?",
"❤️ Benim hangi hareketim kalbini yumuşatıyor?",
"❤️ Birlikte yaşayacağımız ilk şey ne olsun isterdin?",
"❤️ Benim için sakladığın güzel bir düşünce var mı?",
"❤️ Aşkımızı bir renkle anlatsan hangi renk olurdu?",
"❤️ Benimle ilgili en sevdiğin anı nedir?",
"❤️ Beni gördüğünde yüzünde neden gülümseme oluşuyor?",
"❤️ Sana göre mükemmel bir günümüz nasıl olurdu?",
"❤️ Benimle ilgili değiştirmek istemediğin şey nedir?",
"❤️ Birlikte gerçekleştirmek istediğin hedef ne?",
"❤️ Benim yanımda en güvende hissettiğin an hangisi?",
"❤️ Beni tanıdığın için mutlu musun?",
"❤️ Hayatında bana ayırdığın yer ne kadar büyük?",
"❤️ Benim için bir mektup yazsan ilk cümle ne olurdu?",
"❤️ İlişkimizin sana kattığı en güzel şey nedir?",
"❤️ Birlikte kurduğumuz en güzel hayal hangisi?",
"❤️ Benim hangi özelliğim seni etkiliyor?",
"❤️ Beni düşündüğünde aklına gelen ilk şey nedir?",
"❤️ Aşkımızın sembolü ne olabilir?",
"❤️ Benimle ilgili en çok neyi merak ediyorsun?",
"❤️ Seni bana yaklaştıran olay neydi?",
"❤️ Benimle ilgili anlatmaktan hoşlandığın şey nedir?",
"❤️ Birlikte güneşin doğuşunu mu batışını mı izlemek isterdin?",
"❤️ Beni en çok hangi halimle seviyorsun?",
"❤️ Gelecekte birlikte yaşamak istediğin şehir neresi?",
"❤️ İlişkimizde en çok neye önem veriyorsun?",
"❤️ Bana teşekkür etmek istesen neden ederdin?",
"❤️ Benimle ilgili en tatlı detay ne?",
"❤️ Benim yanımda zaman hızlı mı geçiyor?",
"❤️ Birlikte yaşayacağımız en büyük macera ne olabilir?",
"❤️ Benim için aldığın en anlamlı karar neydi?",
"❤️ Sana göre aşkımızı özel yapan şey nedir?",
"❤️ Benimle ilgili ilk anlattığın kişi kimdi?",
"❤️ Birlikte olmasaydık hayatın nasıl olurdu?",
"❤️ Benimle ilgili en çok neyi özlersin?",
"❤️ Beni görünce kalbin hızlanıyor mu?",
"❤️ Aşkımızı anlatan bir kelime seçsen ne olurdu?",
"❤️ Benimle ilgili en sevdiğin fotoğraf hangisi?",
"❤️ Seni bana bağlayan duygu neydi?",
"❤️ Birlikte sahip olmak istediğin şey nedir?",
"❤️ Benimle ilgili değiştirmek istediğin bir şey var mı?",
"❤️ Bana baktığında geleceği görebiliyor musun?",
"❤️ Benim yanımda en rahat hissettiğin an hangisi?",
"❤️ Birlikte yaşayacağımız en güzel yıl hangisi olur?",
"❤️ Benimle ilgili ilk hatıran nedir?",
"❤️ Bana olan sevgini nasıl gösteriyorsun?",
"❤️ Birlikte geçirdiğimiz zamanı özlüyor musun?",
"❤️ Benim için vazgeçebileceğin bir şey var mı?",
"❤️ Hayatında beni tanımlayan kelime ne olurdu?",
"❤️ Benimle ilgili seni mutlu eden detay ne?",
"❤️ Birlikte gerçekleştirmek istediğin hayal ne?",
"❤️ Beni sevdiğini ilk ne zaman fark ettin?",
"❤️ Bana göre aşkın tanımı nedir?",
"❤️ Birlikte sonsuza kadar mutlu olabilir miyiz?",
"❤️ Beni anlatan bir şarkı sözü seçebilir misin?",
"❤️ Senin için aşk mı ben mi?",
"❤️ İlişkimizin en unutulmaz günü hangisi?",

    "❤️ Beni ilk gördüğünde ne hissettin?",
    "❤️ Benimle ilgili en sevdiğin anı hangisi?",
    "❤️ Beni neden seviyorsun?",
    "❤️ Benim hangi davranışım seni mutlu ediyor?",
    "❤️ Bizim hikayemizi tek kelimeyle anlatsan ne derdin?",
    "❤️ Benimle gelecekte nerede olmak isterdin?",
    "❤️ Sana kendini en çok ne zaman özel hissettiriyorum?",
    "❤️ Birlikte yaşlanmayı hayal ediyor musun?",
    "❤️ Bana söylemek istediğin en romantik cümle ne?",
    "❤️ İlişkimizde seni en çok mutlu eden şey ne?",
    "❤️ Benimle ilgili değiştirmek istemediğin şey nedir?",
    "❤️ Beni özlediğinde aklına ilk ne geliyor?",
    "❤️ Bana sarıldığında ne hissediyorsun?",
    "❤️ Aşkımızı bir şarkı anlatsa hangi şarkı olurdu?",
    "❤️ Birlikte kurduğun en güzel hayal ne?",
 "❤️ Benimle ilgili en sevdiğin küçük detay nedir?",
"❤️ Birlikte yaşlanırken en çok neyi paylaşmak isterdin?",
"❤️ Sana göre aşkımızın en özel tarafı nedir?",
"❤️ Benimle ilgili her zaman hatırlamak istediğin şey nedir?",
"❤️ Birlikte gerçekleştireceğimiz ilk büyük hayal ne olsun isterdin?",
"❤️ Benim hangi davranışım sana huzur veriyor?",
"❤️ Beni özlediğinde aklına gelen ilk an hangisi?",
"❤️ Benimle ilgili seni en çok etkileyen şey nedir?",
"❤️ Birlikte yaşayacağımız en mutlu gün nasıl olurdu?",
"❤️ Benim yanımda en çok hangi duyguyu hissediyorsun?",
"❤️ İlk buluşmamızın en güzel kısmı neydi?",
"❤️ Bana dair unutamadığın bir söz var mı?",
"❤️ Benimle ilgili anlatmaktan hoşlandığın şey nedir?",
"❤️ Sana göre aşkımızı güçlü yapan şey nedir?",
"❤️ Birlikte dünyanın herhangi bir yerine gidebilsek nereyi seçerdin?",
"❤️ Benim hangi huyum seni bana daha çok bağlıyor?",
"❤️ İlişkimizde seni en çok mutlu eden alışkanlık nedir?",
"❤️ Bana yazacağın kısa bir aşk mesajı ne olurdu?",
"❤️ Benimle ilgili ilk dikkatini çeken şey neydi?",
"❤️ Birlikte geçirmek istediğin mükemmel gün nasıl olurdu?",
"❤️ Benimle ilgili en sevdiğin anı hangisi?",
"❤️ Bana olan sevgini bir renkle anlatsan hangi renk olurdu?",
"❤️ Benim yanımda kendini neden rahat hissediyorsun?",
"❤️ Aşkımızı bir film sahnesiyle anlatsan nasıl olurdu?",
"❤️ Birlikte gerçekleştirmek istediğin romantik plan nedir?",
"❤️ Bana baktığında gelecekle ilgili ne düşünüyorsun?",
"❤️ Benim hangi özelliğime hayransın?",
"❤️ Birlikte kurduğumuz en güzel hayal hangisiydi?",
"❤️ Beni ilk özlediğini ne zaman fark ettin?",
"❤️ İlişkimizde seni en çok heyecanlandıran şey nedir?",
"❤️ Benimle ilgili en değerli hatıran hangisi?",
"❤️ Sana göre aşkımızı farklı yapan şey nedir?",
"❤️ Benim yanımda zaman neden hızlı geçiyor?",
"❤️ Birlikte yapmak istediğin yeni bir şey var mı?",
"❤️ Bana söylemek istediğin ama ertelediğin bir söz var mı?",
"❤️ Benimle ilgili seni en çok güldüren an hangisiydi?",
"❤️ Birlikte yaşamak istediğin hayalindeki ev nasıl olurdu?",
"❤️ Benimle ilgili en sevdiğin fotoğraf hangisi?",
"❤️ Bana göre romantizmin tanımı nedir?",
"❤️ Aşkımızı anlatan bir kitap adı seçsen ne olurdu?",
"❤️ Benimle ilgili değiştirmek istemediğin şey nedir?",
"❤️ Birlikte yaşlanmak sana ne hissettiriyor?",
"❤️ Benimle ilgili seni en çok etkileyen bakış hangisiydi?",
"❤️ Sana göre ilişkimizin en güçlü yanı nedir?",
"❤️ Bana olan sevgini üç kelimeyle anlatabilir misin?",
"❤️ Benimle ilgili en çok neye güveniyorsun?",
"❤️ Birlikte geçirdiğimiz en unutulmaz gün hangisiydi?",
"❤️ Benim yanımda hissettiğin en güzel duygu nedir?",
"❤️ Aşkımızı bir şarkı sözüyle anlatsan ne derdin?",
"❤️ Benimle gelecekte yapmak istediğin ilk şey nedir?",
  "❤️ Bana dair en sevdiğin anı tekrar yaşayabilsen hangisini seçerdin?",
"❤️ Benimle ilgili seni en çok şaşırtan şey neydi?",
"❤️ İlk kez bana karşı güçlü duygular hissettiğin an hangisiydi?",
"❤️ Birlikte geçirdiğimiz en romantik akşam hangisiydi?",
"❤️ Benim hangi özelliğim seni her gün yeniden etkiliyor?",
"❤️ Sana göre aşkımızın en güzel yanı nedir?",
"❤️ Benimle ilgili aklına gelen ilk güzel anı hangisi?",
"❤️ Bana bir takma ad verecek olsan ne verirdin?",
"❤️ Birlikte yaşlanırken en çok neyi paylaşmak isterdin?",
"❤️ Benimle ilgili anlatmaktan gurur duyduğun şey nedir?",
"❤️ Birlikte kurduğumuz en güzel hayal hangisiydi?",
"❤️ Beni düşündüğünde yüzünde oluşan ilk ifade nedir?",
"❤️ Benim hangi davranışım sana kendini değerli hissettiriyor?",
"❤️ Aşkımızı bir mevsime benzetseydin hangisi olurdu?",
"❤️ Birlikte gitmek istediğin en romantik yer neresi?",
"❤️ Bana söyleyemediğin romantik bir düşüncen var mı?",
"❤️ Benimle ilgili unutamadığın bir bakış var mı?",
"❤️ Sana göre ilişkimizin en güçlü temeli nedir?",
"❤️ Birlikte yaşayacağımız en güzel an henüz gelmedi mi?",
"❤️ Benim yanımda en çok hangi duyguyu hissediyorsun?",
"❤️ Aşkımızı anlatan bir film olsa adı ne olurdu?",
"❤️ Benimle ilgili seni en çok mutlu eden detay nedir?",
"❤️ Birlikte gerçekleştirmek istediğin en büyük hayal nedir?",
"❤️ Bana göre aşkın gerçek tanımı nedir?",
"❤️ Benimle ilgili ilk anlattığın kişi kimdi?",
"❤️ Bana sarıldığında zamanın durduğunu hissediyor musun?",
"❤️ İlişkimizde seni en çok heyecanlandıran şey nedir?",
"❤️ Benimle ilgili en sevdiğin alışkanlık nedir?",
"❤️ Beni ilk özlediğin günü hatırlıyor musun?",
"❤️ Aşkımızı bir renk olarak düşünsen hangi renk olurdu?",
"❤️ Birlikte yaşamak istediğin hayalindeki gün nasıl geçerdi?",
"❤️ Benimle ilgili seni en çok etkileyen söz hangisiydi?",
"❤️ Bana olan sevgini anlatan bir şarkı seçebilir misin?",
"❤️ Benim hangi özelliğimi gelecekte de seveceğini düşünüyorsun?",
"❤️ Sana göre ilişkimizin en unutulmaz günü hangisiydi?",
"❤️ Beni gördüğünde ilk dikkat ettiğin şey ne oluyor?",
"❤️ Benimle ilgili seni en çok güldüren an hangisiydi?",
"❤️ Birlikte kuracağımız gelecekte en çok neyi bekliyorsun?",
"❤️ Bana göre mutluluğun tanımı nedir?",
"❤️ Benimle ilgili kalbinde sakladığın en güzel düşünce nedir?",
"❤️ Aşkımızı tek bir cümleyle anlatabilir misin?",
"❤️ Benimle ilgili en sevdiğin tesadüf nedir?",
"❤️ Birlikte geçirdiğimiz zamanın en değerli kısmı nedir?",
"❤️ Bana teşekkür etmek istesen hangi konu için ederdin?",
"❤️ Benimle ilgili seni en çok etkileyen an hangisiydi?",
"❤️ Sana göre aşkımızı güçlü tutan şey nedir?",
"❤️ Beni hayatında görmek neden önemli?",
"❤️ Birlikte gerçekleştireceğimiz ilk büyük hedef ne olsun isterdin?",
"❤️ Benim yanımda hissettiğin huzuru nasıl tarif edersin?",
"❤️ Gelecekte bizi düşündüğünde seni en çok ne mutlu ediyor?",
"❤️ Benimle ilgili seni en çok heyecanlandıran şey nedir?",
"❤️ Bana ilk kez âşık olduğunu ne zaman hissettin?",
"❤️ Birlikte geçirdiğimiz hangi günü tekrar yaşamak isterdin?",
"❤️ Benim hangi davranışım kalbini yumuşatıyor?",
"❤️ Sana göre aşkımızın en özel hatırası hangisi?",
"❤️ Benimle ilgili en sevdiğin sürpriz neydi?",
"❤️ Birlikte yaşlanırken en çok hangi anıları anlatmak isterdin?",
"❤️ Bana baktığında geleceğimiz hakkında ne düşünüyorsun?",
"❤️ Benim hangi özelliğimi ilk fark etmiştin?",
"❤️ Birlikte yaşayacağımız en güzel tatil nasıl olurdu?",
"❤️ Bana göre romantik bir akşam nasıl geçmeli?",
"❤️ Benimle ilgili seni en çok etkileyen iltifat neydi?",
"❤️ Sana göre ilişkimizin en tatlı alışkanlığı nedir?",
"❤️ Beni özlediğinde en çok neyi özlüyorsun?",
"❤️ Birlikte kurduğumuz hayallerden hangisi seni en çok heyecanlandırıyor?",
"❤️ Benimle ilgili unutamadığın ilk duygu nedir?",
"❤️ Aşkımızı bir şehirle anlatsan hangi şehir olurdu?",
"❤️ Benim yanımda kendini en çok ne zaman mutlu hissediyorsun?",
"❤️ Bana göre sadakatin anlamı nedir?",
"❤️ Birlikte yaşayacağımız en güzel yıl hangisi olurdu?",
"❤️ Benimle ilgili seni en çok gururlandıran şey nedir?",
"❤️ Sana göre aşkımızın en güçlü yönü nedir?",
"❤️ Bana söylemek istediğin en içten teşekkür ne olurdu?",
"❤️ Benimle ilgili en çok hangi anı saklamak isterdin?",
"❤️ Birlikte geçirdiğimiz en huzurlu an hangisiydi?",
"❤️ Beni anlatan bir şarkı seçsen hangisi olurdu?",
"❤️ Benim hangi özelliğimi hiç değişmesin diye isterdin?",
"❤️ Sana göre ilişkimizin en romantik detayı nedir?",
"❤️ Bana sarıldığında hissettiğin ilk duygu nedir?",
"❤️ Birlikte gerçekleştirmek istediğin romantik plan nedir?",
"❤️ Benimle ilgili seni en çok şaşırtan güzel şey nedir?",
"❤️ Aşkımızı bir çiçekle anlatsan hangisi olurdu?",
"❤️ Benim yanımda kendini neden güvende hissediyorsun?",
"❤️ Sana göre birlikte kurduğumuz en değerli şey nedir?",
"❤️ Beni ilk kez özlediğini ne zaman fark ettin?",
"❤️ Benimle ilgili en çok neye hayransın?",
"❤️ Birlikte yaşayacağımız bir günü tasvir etsen nasıl olurdu?",
"❤️ Bana göre aşkın en güzel hali nedir?",
"❤️ Benimle ilgili seni en çok mutlu eden mesaj hangisiydi?",
"❤️ Sana göre ilişkimizin en unutulmaz anı hangisi?",
"❤️ Beni düşündüğünde aklına gelen ilk görüntü nedir?",
"❤️ Benimle ilgili sevdiğin küçük bir detay nedir?",
"❤️ Birlikte olmak sana ne kazandırdı?",
"❤️ Bana karşı hissettiğin en güçlü duygu nedir?",
"❤️ Benimle ilgili en çok neyi merak etmeye devam ediyorsun?",
"❤️ Sana göre mükemmel bir sevgili nasıl olur?",
"❤️ Benim hangi davranışım seni bana daha çok bağlıyor?",
"❤️ Birlikte yaşayacağımız en güzel sürpriz ne olabilir?",
"❤️ Bana olan sevgini anlatan üç kelime nedir?",
"❤️ Gelecekte bizi düşündüğünde seni en çok heyecanlandıran şey nedir?",
],

  eglenceli: [
    "😂 Birlikte bir oyun programına katılsak ilk soruda elenir miydik?",
"😂 Hangimiz daha çok yanlış kişiye mesaj atabilir?",
"😂 Birlikte bir gün boyunca telefon kullanmasak ne olurdu?",
"😂 Hangimiz daha çok gizli gizli atıştırır?",
"😂 Birlikte bir restoranı eleştirsek en çok neyi konuşurduk?",
"😂 Benim en komik alışkanlığım hangisi?",
"😂 Birlikte bir dedektiflik görevine çıksak ilk ipucunu kim bulurdu?",
"😂 Hangimiz daha çok saçma bahane üretir?",
"😂 Birlikte canlı yayına çıksak en komik olay ne olurdu?",
"😂 Hangimiz daha çok unutkan?",
"😂 Birlikte yanlışlıkla aynı kıyafeti giysek ne yapardık?",
"😂 Benim en komik takıntım ne olabilir?",
"😂 Birlikte alışverişe çıksak kim daha fazla para harcardı?",
"😂 Hangimiz daha çok yönünü kaybeder?",
"😂 Birlikte bir yarışma sunsak adı ne olurdu?",
"😂 Benim en komik korkum ne olabilir?",
"😂 Birlikte bir gün boyunca rol değiştirseydik ne olurdu?",
"😂 Hangimiz daha çok kahkaha krizine girer?",
"😂 Birlikte bir müzik grubu kursak adımız ne olurdu?",
"😂 Benim en komik yüz ifadem hangisi?",
"😂 Birlikte bir kafede çalışsak ilk gün ne olurdu?",
"😂 Hangimiz daha çok yanlış anlar?",
"😂 Birlikte dünya turuna çıksak en komik olay hangi ülkede yaşanırdı?",
"😂 Benim en komik refleksim ne olabilir?",
"😂 Birlikte bir film çeksek ilk sahne ne olurdu?",
"😂 Hangimiz daha çok abartmayı sever?",
"😂 Birlikte uzayda yaşasak ilk kavga sebebimiz ne olurdu?",
"😂 Benim en komik mesajım ne olabilir?",
"😂 Birlikte bir hayvanat bahçesinde gece kalsak ne yapardık?",
"😂 Hangimiz daha çok meraklı?",
"😂 Birlikte yanlışlıkla ünlü olsak neyle tanınırdık?",
"😂 Benim en komik çocukluk hikayem ne olabilir?",
"😂 Birlikte bir kafe açsak en ilginç ürünümüz ne olurdu?",
"😂 Hangimiz daha çok şaka kurbanı olur?",
"😂 Birlikte bir adada mahsur kalsak ilk görev dağılımı nasıl olurdu?",
"😂 Benim en komik sinirlenme şeklim ne olabilir?",
"😂 Birlikte bir yarış arabasına binsak kim daha çok bağırırdı?",
"😂 Hangimiz daha çok geç kalır?",
"😂 Birlikte sadece emoji kullanarak konuşsak ilk yanlış anlaşılma ne olurdu?",
"😂 Benim en komik alışverişim ne olabilir?",
"😂 Birlikte bir lunaparkta gece kalsak ne yapardık?",
"😂 Hangimiz daha çok sürpriz sever?",
"😂 Birlikte yanlış trene binsak nasıl kurtulurduk?",
"😂 Benim en komik kıskançlık anım nasıl olurdu?",
"😂 Birlikte bir kamp ateşi başında en çok neye gülerdik?",
"😂 Hangimiz daha çok macera arar?",
"😂 Birlikte bir komedi dizisinde oynasak karakterlerimiz nasıl olurdu?",
"😂 Benim en komik lakabım ne olabilir?",
"😂 Birlikte bir karaoke gecesinde hangi şarkıyı mahvederdik?",
"😂 Hangimiz daha çok selfie çeker?",
"😂 Birlikte yanlışlıkla bir yarışma kazansak ödülle ne yapardık?",
"😂 Benim en komik yanlış anlamam ne olabilir?",
"😂 Birlikte bir mağazada kilitli kalsak ne yapardık?",
"😂 Hangimiz daha çok hayal kurar?",
"😂 Birlikte bir vlog çeksek ilk bölümün konusu ne olurdu?",
"😂 Benim en komik uyku alışkanlığım ne olabilir?",
"😂 Birlikte bir piknikte en komik olay ne olurdu?",
"😂 Hangimiz daha çok sabırsız?",
"😂 Birlikte bir tiyatro oyununda oynasak kim repliği unuturdu?",
"😂 Benim en komik taklidim hangi ünlü olurdu?",
"😂 Birlikte bir oyun gecesi düzenlesek kim kazanırdı?",
"😂 Hangimiz daha çok inatçı?",
"😂 Birlikte bir dedektif dizisinde oynasak kim suçluyu bulurdu?",
"😂 Benim en komik sakarlığım ne olabilir?",
"😂 Birlikte bir ev dekorasyon programı yapsak sonuç nasıl olurdu?",
"😂 Hangimiz daha çok konuşur?",
"😂 Birlikte bir korku evine girsek ilk kim kaçardı?",
"😂 Benim en komik bahane üretme şeklim ne olabilir?",
"😂 Birlikte bir şehirde kaybolsak kim yön bulurdu?",
"😂 Hangimiz daha çok heyecanlanır?",
"😂 Birlikte bir aşçılık yarışmasına katılsak ne pişirirdik?",
"😂 Benim en komik moda seçimim ne olabilir?",
"😂 Birlikte bir teknoloji fuarına gitsek ilk neyi denerdik?",
"😂 Hangimiz daha çok şanslı?",
"😂 Birlikte bir fotoğraf çekiminde en komik poz ne olurdu?",
"😂 Benim en komik alışkanlığım hangisi?",
"😂 Birlikte bir otelde yanlış odaya girsek ne olurdu?",
"😂 Hangimiz daha çok dikkat çeker?",
"😂 Birlikte bir sürpriz parti hazırlasak kim sırrı bozardı?",
"😂 Benim en komik araba kullanma huyum ne olabilir?",
"😂 Birlikte bir müzede gece kalsak ilk ne yapardık?",
"😂 Hangimiz daha çok plan yapar?",
"😂 Birlikte bir hayali şirket kursak adı ne olurdu?",
"😂 Benim en komik yemek yapma hatam ne olabilir?",
"😂 Birlikte bir oyun karakteri tasarlasak özellikleri ne olurdu?",
"😂 Hangimiz daha çok rekabetçi?",
"😂 Birlikte bir havaalanında mahsur kalsak nasıl eğlenirdik?",
"😂 Benim en komik unutkanlık hikayem ne olabilir?",
"😂 Birlikte bir alışveriş merkezinde saklambaç oynasak kim kazanırdı?",
"😂 Hangimiz daha çok spontane davranır?",
"😂 Birlikte bir festivalde kaybolsak ilk ne yapardık?",
"😂 Benimle ilgili seni en çok güldüren olay hangisi?",
"😂 Birlikte bir gün boyunca sadece şarkı sözleriyle konuşsak ne olurdu?",
"😂 Hangimiz daha çok komik durumlara düşer?",
"😂 Birlikte zaman makinesi bulsak ilk hangi yıla giderdik?",
"😂 Benim en komik huyumun Oscar ödülü alsa adı ne olurdu?",
"😂 Beraber görünmez olsak ilk ne yapardık?",
"😂 Hangimiz daha çok yemek yer?",
"😂 Bir günlüğüne yer değiştirsek ilk ne yapardın?",
"😂 Benim en komik huyum ne?",
"😂 Bir filmde çift olsak hangi film olurdu?",
"😂 Hangimiz daha çok trip atar?",
"😂 Birlikte tatile çıksak en çok neye gülerdik?",
"😂 Beni bir çizgi film karakterine benzetseydin kim olurdum?",
"😂 En saçma ama komik anımız hangisi?",
"😂 Beraber çocuk olsak ne yapardık?",
"😂 Hangimiz daha fazla uyur?",
"😂 Birlikte komik bir video çeksek konusu ne olurdu?",
"😂 Benimle dalga geçtiğin en tatlı şey ne?",
"😂 Beraber kaybolsak hangimiz yolu bulurdu?",
"😂 Bir yarışmaya katılsak kim kazanırdı?",
"😂 Hangimiz daha çok sakarlık yapar?",
"😂 Birlikte kamp yapsak ilk kriz ne olurdu?",
"😂 Benim en komik sözüm hangisi?",
"😂 Aynı evde mahsur kalsak nasıl eğlenirdik?",
"😂 Hangimiz daha çok telefonuna bakıyor?",
"😂 Birlikte restoran açsak adı ne olurdu?",
"😂 Hangimiz daha çok alışveriş yapar?",
"😂 Bir gün boyunca sadece emojiyle konuşsak ne olurdu?",
"😂 Beni bir hayvana benzetseydin hangisi olurdum?",
"😂 Birlikte karaoke yapsak ilk hangi şarkıyı söylerdik?",
"😂 Hangimiz daha çok unutkan?",
"😂 Birlikte YouTube kanalı açsak içeriği ne olurdu?",
"😂 Benim en komik alışkanlığım nedir?",
"😂 Birlikte oyun oynasak kim hile yapardı?",
"😂 Hangimiz daha çok geç kalır?",
"😂 Birlikte gizli ajan olsak görevimiz ne olurdu?",
"😂 Benim en komik fotoğrafım hangisi?",
"😂 Birlikte lunaparka gitsek ilk hangi oyuncağa binerdik?",
"😂 Hangimiz daha çok korkar?",
"😂 Birlikte yanlış otobüse binsak ne yapardık?",
"😂 Benim en saçma korkum ne olabilir?",
"😂 Birlikte dünya turuna çıksak ilk nerede kaybolurduk?",
"😂 Hangimiz daha çok şaka yapar?",
"😂 Birlikte pizza yapsak sonuç nasıl olurdu?",
"😂 Benim en komik mesajım hangisiydi?",
"😂 Birlikte yarış arabasına binsak kim çığlık atardı?",
"😂 Hangimiz daha çok selfie çeker?",
"😂 Birlikte dizi çeksek adı ne olurdu?",
"😂 Benim en komik taklidim ne olabilir?",
"😂 Birlikte sahneye çıksak ne yapardık?",
"😂 Hangimiz daha çok meraklı?",
"😂 Birlikte gizli bir kulüp kursak adı ne olurdu?",
"😂 Benimle ilgili en komik anın hangisi?",
"😂 Birlikte oyun karakteri olsak özelliklerimiz ne olurdu?",
"😂 Hangimiz daha çok abartır?",
"😂 Birlikte gece yarısı acıksak ne yerdik?",
"😂 Benim en komik yüz ifadem hangisi?",
"😂 Birlikte uzaya gitsek ilk ne yapardık?",
"😂 Hangimiz daha çok konuşur?",
"😂 Birlikte hayalet avına çıksak ne olurdu?",
"😂 Benim en komik lakabım ne olurdu?",
"😂 Birlikte okulda olsak hangi dersten kalırdık?",
"😂 Hangimiz daha çok kahkaha atar?",
"😂 Birlikte markete gidip sadece 50 TL harcasak ne alırdık?",
"😂 Benim en komik huyum hangisi?",
"😂 Birlikte parti düzenlesek teması ne olurdu?",
"😂 Hangimiz daha çok uyurgezer olabilir?",
"😂 Birlikte bir uygulama kursak adı ne olurdu?",
"😂 Benim en komik çocukluk hikayem ne olabilir?",
"😂 Birlikte çölde kalsak ilk ne yapardık?",
"😂 Hangimiz daha çok yemek seçer?",
"😂 Birlikte şarkı yazsak adı ne olurdu?",
"😂 Benim en komik kıskançlık anım ne olurdu?",
"😂 Birlikte sabaha kadar uyumasak ne yapardık?",
"😂 Hangimiz daha çok heyecanlanır?",
"😂 Birlikte yanlışlıkla ünlü olsak ne olurdu?",
"😂 Benim en komik takıntım ne olabilir?",
"😂 Birlikte spor yapsak kim pes ederdi?",
"😂 Hangimiz daha çok televizyon izler?",
"😂 Birlikte bir kafe açsak menüde ne olurdu?",
"😂 Benim en komik rüyam ne olabilir?",
"😂 Birlikte define arasak ne bulurduk?",
"😂 Hangimiz daha çok yön duygusunu kaybeder?",
"😂 Birlikte korku filmine girsek ilk kim kaçardı?",
"😂 Benim en komik sinirlenme şeklim ne olurdu?",
"😂 Birlikte bir ada satın alsak adını ne koyardık?",
"😂 Hangimiz daha çok sürpriz yapar?",
"😂 Birlikte moda tasarlasak nasıl olurdu?",
"😂 Benim en komik yanlış anlamam ne olabilir?",
"😂 Birlikte havaalanında mahsur kalsak ne yapardık?",
"😂 Hangimiz daha çok maceracı?",
"😂 Birlikte bir yarışma sunsak adı ne olurdu?",
"😂 Benim en komik refleksim ne olabilir?",
"😂 Birlikte evcil hayvan alsak adı ne olurdu?",
"😂 Hangimiz daha çok şanslı?",
"😂 Birlikte komedi filminde oynasak rollerimiz ne olurdu?",
"😂 Benim en komik özelliğim nedir?",
"😂 Birlikte çocuk parkına gitsek ilk ne yapardık?",
"😂 Hangimiz daha çok inatçı?",
"😂 Birlikte emoji dili oluştursak ilk kuralı ne olurdu?",
"😂 Benimle ilgili seni en çok güldüren şey nedir?",
"😂 Birlikte zaman makinesi bulsak ilk hangi yıla giderdik?",

    "😂 Beraber görünmez olsak ilk ne yapardık?",
    "😂 Hangimiz daha çok trip atar?",
    "😂 Benim en komik huyum ne?",
    "😂 Bir filmde çift olsak hangi film olurdu?",
    "😂 Beraber tatile çıksak en çok neye gülerdik?",
    "😂 Hangimiz daha çok yemek yer?",
    "😂 Bir günlüğüne yer değiştirsek ilk ne yapardın?",
    "😂 Beraber yarışmaya katılsak kim kazanırdı?",
    "😂 Beni bir çizgi film karakterine benzetseydin kim olurdum?",
    "😂 En saçma ama komik anımız hangisi?",
    "😂 Beraber çocuk olsak ne yapardık?",
    "😂 Hangimiz daha fazla uyur?",
    "😂 Birlikte komik bir video çeksek konusu ne olurdu?",
    "😂 Benimle dalga geçtiğin en tatlı şey ne?",
    "😂 Beraber kaybolsak hangimiz yolu bulurdu?",
  ],

  derin: [
    "🌙 Sence hayatın en önemli amacı nedir?",
"🌙 Kendini gerçekten tanıdığını düşünüyor musun?",
"🌙 Hayatında seni en çok zorlayan karar neydi?",
"🌙 Bir insanı gerçekten mutlu eden şey nedir?",
"🌙 Gelecekteki hayatından en büyük beklentin nedir?",
"🌙 Kendini en çok hangi konuda eleştiriyorsun?",
"🌙 İnsan neden bazen kendinden uzaklaşır?",
"🌙 Hayatında seni en çok etkileyen söz neydi?",
"🌙 Sence bir insanın en büyük zenginliği nedir?",
"🌙 Kendini en çok ne zaman yalnız hissettin?",
"🌙 Geçmişte değiştirmek istediğin bir olay var mı?",
"🌙 Sence insan neden hata yapar?",
"🌙 Bir insanı affetmek her zaman mümkün müdür?",
"🌙 Hayatında seni en çok ne güçlendirdi?",
"🌙 İnsanların seni anlamasını istediğin şey nedir?",
"🌙 Sence mutluluk bir seçim midir?",
"🌙 En büyük içsel savaşın nedir?",
"🌙 Kendini en çok ne zaman huzurlu hissediyorsun?",
"🌙 Bir günlüğüne tüm korkuların kaybolsa ne yapardın?",
"🌙 Sence hayat tesadüflerden mi oluşur?",
"🌙 İnsan neden geçmişine takılı kalır?",
"🌙 Kendinle ilgili en çok sevdiğin özellik nedir?",
"🌙 Hayatında seni en çok ne şaşırttı?",
"🌙 Bir insanın karakteri en çok ne zaman belli olur?",
"🌙 Sence gerçek cesaret nedir?",
"🌙 Hayatındaki en büyük dönüm noktası hangisiydi?",
"🌙 Bir insanın kalbi nasıl iyileşir?",
"🌙 Sence insanlar neden değişir?",
"🌙 Gelecekte kendin için ne diliyorsun?",
"🌙 Hayatında seni en çok ne motive ediyor?",
"🌙 Bir insanı gerçekten özel yapan şey nedir?",
"🌙 Kendini en çok hangi konuda geliştirmek istiyorsun?",
"🌙 Sence güven kaybolunca geri gelir mi?",
"🌙 İnsan neden bazen kendi mutluluğunu erteler?",
"🌙 Hayatında seni en çok etkileyen an hangisiydi?",
"🌙 Bir şeyi yeniden yaşayabilsen hangisini seçerdin?",
"🌙 Kendine en çok hangi konuda haksızlık yaptın?",
"🌙 Sence umut olmasaydı insanlar nasıl yaşardı?",
"🌙 Hayatında seni en çok ne değiştirdi?",
"🌙 İnsan neden sevdiklerini kaybetmekten korkar?",
"🌙 Kendinle gurur duyduğun bir anı anlatır mısın?",
"🌙 Bir insanı gerçekten tanımak ne kadar sürer?",
"🌙 Sence kalp mi mantık mı daha çok kazanır?",
"🌙 Hayatında öğrendiğin en değerli ders nedir?",
"🌙 İnsan neden bazen yalnız kalmaya ihtiyaç duyar?",
"🌙 Geleceğe dair seni en çok heyecanlandıran şey nedir?",
"🌙 Sence gerçek özgürlük nedir?",
"🌙 Kendini en çok hangi ortamda ait hissediyorsun?",
"🌙 Bir insanın en büyük korkusu ne olabilir?",
"🌙 Hayatında seni en çok ne ilham veriyor?",
"🌙 Sence insanlar neden hayal kurar?",
"🌙 Bir günlüğüne geçmişe dönebilseydin ne yapardın?",
"🌙 Kendin hakkında keşfetmek istediğin şey nedir?",
"🌙 Sence sevgi insanı iyileştirir mi?",
"🌙 İnsan neden bazen risk almaktan korkar?",
"🌙 Hayatında seni en çok mutlu eden başarı nedir?",
"🌙 Sence zaman her yarayı sarar mı?",
"🌙 Kendini en çok hangi konuda güçlü hissediyorsun?",
"🌙 Bir insanın hayatında en önemli şey nedir?",
"🌙 Hayatında seni en çok ne olgunlaştırdı?",
"🌙 İnsan neden bazı anıları unutamaz?",
"🌙 Sence fedakârlığın bir sınırı olmalı mı?",
"🌙 Kendini en çok ne zaman özgür hissettin?",
"🌙 Bir insanı gerçekten iyi yapan şey nedir?",
"🌙 Hayatındaki en büyük hayal nedir?",
"🌙 İnsan neden bazen geçmişte yaşar?",
"🌙 Sence başarıyı nasıl tanımlarsın?",
"🌙 Kendine söylemek istediğin bir şey var mı?",
"🌙 Bir insanın kendini bulması ne demektir?",
"🌙 Hayatında seni en çok etkileyen kişi kimdi?",
"🌙 İnsan neden değişmek ister?",
"🌙 Sence dürüstlük her zaman doğru sonuç verir mi?",
"🌙 Kendini en çok hangi konuda yetersiz hissediyorsun?",
"🌙 Bir insanın en büyük gücü nedir?",
"🌙 Hayatında seni en çok ne korkutuyor?",
"🌙 İnsan neden bağ kurmaya ihtiyaç duyar?",
"🌙 Sence gerçek sadakat nedir?",
"🌙 Kendini en çok ne zaman güçlü hissettin?",
"🌙 Bir günlüğüne tüm sorumlulukların kalksa ne yapardın?",
"🌙 Hayatında seni en çok ne şaşırttı?",
"🌙 İnsan neden bazen susmayı seçer?",
"🌙 Sence mutluluğun formülü var mı?",
"🌙 Kendinle ilgili değiştirmek istediğin şey nedir?",
"🌙 Bir insanın en değerli özelliği nedir?",
"🌙 Hayatında seni en çok ne umutlandırıyor?",
"🌙 İnsan neden bazen korkularına yenilir?",
"🌙 Sence sevginin en güçlü hali nedir?",
"🌙 Kendine verdiğin en önemli söz nedir?",
"🌙 Bir insanın hayatındaki en büyük başarı nedir?",
"🌙 Hayatında seni en çok ne etkiledi?",
"🌙 İnsan neden affetmekte zorlanır?",
"🌙 Sence huzurlu bir hayat nasıl olur?",
"🌙 Kendini en çok hangi konuda tanıyorsun?",
"🌙 Bir insanın en büyük hayali ne olmalı?",
"🌙 Hayatında seni en çok değiştiren kişi kimdi?",
"🌙 Sence iyi bir insan olmak ne demektir?",
"🌙 Gelecekte hatırlanmak istediğin şey nedir?",
"🌙 Hayatında seni en çok değiştiren olay neydi?",
"🌙 Kendin hakkında öğrendiğin en önemli şey nedir?",
"🌙 Sence gerçek mutluluk nedir?",
"🌙 En büyük korkun nedir?",
"🌙 Gelecekteki kendine ne söylemek isterdin?",
"🌙 İnsanları affetmek neden zor olabilir?",
"🌙 Hayatında en çok neye minnettarsın?",
"🌙 Sence insanı güçlü yapan şey nedir?",
"🌙 En çok anlaşılmak istediğin konu nedir?",
"🌙 Çocukluğundaki hangi an seni bugün de etkiliyor?",
"🌙 Kendini en huzurlu hissettiğin yer neresi?",
"🌙 Sence sevgi öğrenilen bir şey mi?",
"🌙 Hayatındaki en büyük ders neydi?",
"🌙 Vazgeçmek mi yoksa mücadele etmek mi daha zor?",
"🌙 En büyük hayalin nedir?",
"🌙 Seni geceleri düşündüren konu nedir?",
"🌙 Sence başarı nedir?",
"🌙 Bir şeyi değiştirebilseydin neyi değiştirirdin?",
"🌙 İnsanların seni yanlış anladığı bir konu var mı?",
"🌙 Kendini en yalnız hissettiğin an neydi?",
"🌙 Sence güven nasıl kazanılır?",
"🌙 Bir insanı gerçekten tanımak mümkün mü?",
"🌙 Hayatında dönüm noktası olan olay hangisiydi?",
"🌙 Gelecekle ilgili en büyük umudun nedir?",
"🌙 Sence kader var mı?",
"🌙 Kendinde geliştirmek istediğin yön nedir?",
"🌙 En çok hangi duyguyla mücadele ediyorsun?",
"🌙 Hayatında unutamadığın öğüt nedir?",
"🌙 Bir günlüğüne görünmez olsan ne yapardın?",
"🌙 Sence insan neden sevilmek ister?",
"🌙 Hayatının amacı ne olabilir?",
"🌙 En büyük pişmanlığın nedir?",
"🌙 Kendinle gurur duyduğun şey nedir?",
"🌙 Sence dürüstlük her zaman doğru seçim midir?",
"🌙 En çok hangi konuda cesur olmak isterdin?",
"🌙 Birine vereceğin en değerli tavsiye ne olurdu?",
"🌙 Hayatında seni motive eden şey nedir?",
"🌙 Geçmişine dönsen kendine ne söylerdin?",
"🌙 Sence insanlar neden değişir?",
"🌙 En çok hangi anında kendin gibi hissettin?",
"🌙 Seni en çok ne korkutur?",
"🌙 Bir insanın kalbini güzel yapan şey nedir?",
"🌙 En çok neyi kaybetmekten korkuyorsun?",
"🌙 Sence sadakat ne demektir?",
"🌙 Hayatında seni en çok etkileyen kişi kimdi?",
"🌙 Bir günlüğüne tüm korkuların yok olsa ne yapardın?",
"🌙 Sence umut neden önemlidir?",
"🌙 Kendini tanımlayan üç özellik nedir?",
"🌙 Hayatında en çok neyi başarmak istiyorsun?",
"🌙 Sence mutluluk kalıcı olabilir mi?",
"🌙 Kendinle ilgili değiştirmek istemediğin şey nedir?",
"🌙 En çok hangi konuda anlaşılmak istiyorsun?",
"🌙 Bir şeyi yeniden yaşayabilsen neyi seçerdin?",
"🌙 Hayatındaki en değerli anı nedir?",
"🌙 Sence sevgi mi saygı mı daha önemlidir?",
"🌙 İnsanlar neden yalnız hisseder?",
"🌙 Birine tamamen güvenmek mümkün mü?",
"🌙 En büyük hayal kırıklığın neydi?",
"🌙 Hayatında seni en çok ne olgunlaştırdı?",
"🌙 Sence insanın kendini bulması ne demektir?",
"🌙 Bir şeyi sonsuza kadar hatırlamak istesen neyi seçerdin?",
"🌙 Hayatında en çok kimi özlüyorsun?",
"🌙 Sence fedakârlığın sınırı olmalı mı?",
"🌙 Kendine verdiğin en önemli söz nedir?",
"🌙 Bir insanı özel yapan şey nedir?",
"🌙 Sence zaman her şeyi iyileştirir mi?",
"🌙 Hayatında seni en çok ne mutlu etti?",
"🌙 İnsan neden hayal kurar?",
"🌙 Gelecekteki hayatını tek cümleyle anlatsan ne derdin?",
"🌙 En çok hangi konuda sabırlısın?",
"🌙 Bir insanın karakteri nasıl anlaşılır?",
"🌙 Sence aşk insanı değiştirir mi?",
"🌙 Kendini en güçlü hissettiğin an hangisiydi?",
"🌙 Hayatındaki en büyük mücadele neydi?",
"🌙 Bir şeyi geride bırakmak neden zor olur?",
"🌙 Sence huzur nedir?",
"🌙 Hayatında seni en çok etkileyen kitap veya film hangisiydi?",
"🌙 Kendini geliştirmek için ne yapıyorsun?",
"🌙 En çok hangi değere önem veriyorsun?",
"🌙 Bir insanın gerçek yüzü ne zaman ortaya çıkar?",
"🌙 Hayatında seni en çok ne şaşırttı?",
"🌙 Sence mutluluğun sırrı nedir?",
"🌙 Geçmişte yaptığın hangi seçim seni bugün etkiliyor?",
"🌙 İnsan neden korkularıyla yüzleşmeli?",
"🌙 En büyük içsel gücün nedir?",
"🌙 Hayatında seni en çok ne ilham veriyor?",
"🌙 Sence başarı ve mutluluk aynı şey mi?",
"🌙 Kendini en özgür hissettiğin an hangisiydi?",
"🌙 Bir günlüğüne tüm sorumlulukların kalksa ne yapardın?",
"🌙 Hayatında seni en çok ne değiştirdi?",
"🌙 İnsan neden umut etmeye devam eder?",
"🌙 Sence sevginin en saf hali nedir?",
"🌙 Kendine teşekkür etmek istesen hangi konu için ederdin?",
"🌙 Bir günlüğüne geçmişte yaşayabilsen hangi dönemi seçerdin?",
"🌙 Hayatında seni en çok ne güçlendirdi?",
"🌙 Sence iyi bir insan olmak ne demektir?",
"🌙 Gelecekte hatırlanmak istediğin şey nedir?",

    "🌙 İlişkimiz sana ne öğretti?",
    "🌙 Sence gerçek sevgi nedir?",
    "🌙 Bana en çok hangi konuda güveniyorsun?",
    "🌙 Benden en çok ne bekliyorsun?",
    "🌙 Gelecekte bizim için en büyük hayalin ne?",
    "🌙 Kendini benim yanımda nasıl hissediyorsun?",
    "🌙 İlişkimizde en güçlü yanımız ne?",
    "🌙 Bana söylemek isteyip söyleyemediğin bir şey var mı?",
    "🌙 Zor zamanlarda sana nasıl daha iyi destek olabilirim?",
    "🌙 Sence bizi özel yapan şey ne?",
    "🌙 İlişkimizde neyi daha iyi yapabiliriz?",
    "🌙 Hayatında benim yerim nasıl bir yerde?",
    "🌙 Bana karşı en çok neye değer veriyorsun?",
    "🌙 Birlikte aşmamız gereken en önemli şey ne?",
    "🌙 Kalbin bana en çok ne söylemek isterdi?",
  ],

  cesur: [
    "🔥 Bana karşı hissettiğin en beklenmedik duygu neydi?",
"🔥 Beni ilk gördüğünde en çok hangi detay dikkatini çekti?",
"🔥 Bana dair aklından çıkmayan bir anı var mı?",
"🔥 Aramızdaki çekimi bir film sahnesiyle anlatsan nasıl olurdu?",
"🔥 Bana söylemek isteyip hâlâ söylemediğin bir şey var mı?",
"🔥 Beni en çok hangi halimle çekici buluyorsun?",
"🔥 Bana karşı hislerinin değiştiğini ilk ne zaman fark ettin?",
"🔥 Beni düşündüğünde yüzünde oluşan ilk ifade nedir?",
"🔥 Aramızdaki bağı özel yapan en önemli şey nedir?",
"🔥 Bana karşı en dürüst düşüncen nedir?",
"🔥 Beni özlediğinde ilk hangi anı hatırlıyorsun?",
"🔥 Bana dair en sevdiğin detay hangisi?",
"🔥 Aramızdaki en unutulmaz bakışma hangisiydi?",
"🔥 Beni neden farklı görüyorsun?",
"🔥 Bana karşı hissettiğin en yoğun heyecan ne zamandı?",
"🔥 Benim hangi özelliğim seni şaşırtıyor?",
"🔥 Bana dair en tatlı düşüncen nedir?",
"🔥 Aramızdaki enerjiyi üç kelimeyle anlatır mısın?",
"🔥 Bana baktığında geleceği hayal ediyor musun?",
"🔥 Beni ilk özlediğin günü hatırlıyor musun?",
"🔥 Bana karşı en cesur hayalin nedir?",
"🔥 Benim hangi davranışım seni etkiliyor?",
"🔥 Aramızdaki en güçlü bağ nedir?",
"🔥 Bana dair unutamadığın ilk izlenim nedir?",
"🔥 Beni düşündüğünde aklına gelen ilk kelime nedir?",
"🔥 Bana karşı hislerini anlatan bir şarkı var mı?",
"🔥 Beni en çok ne zaman merak ediyorsun?",
"🔥 Aramızdaki ilişkiyi özel yapan şey nedir?",
"🔥 Bana dair en çok neyi seviyorsun?",
"🔥 Beni gördüğünde neden mutlu oluyorsun?",
"🔥 Bana karşı hissettiğin ilk güçlü duygu neydi?",
"🔥 Benim hangi bakışım aklında kaldı?",
"🔥 Aramızdaki çekimi neye benzetirsin?",
"🔥 Bana dair seni en çok etkileyen an hangisiydi?",
"🔥 Beni düşündüğünde kalbin ne söylüyor?",
"🔥 Bana karşı hislerini bir renkle anlatsan hangi renk olurdu?",
"🔥 Benim hangi özelliğim seni bana bağlıyor?",
"🔥 Aramızdaki en özel sır nedir?",
"🔥 Bana dair hayal kurduğun oluyor mu?",
"🔥 Beni ilk gördüğün anı tekrar yaşamak ister miydin?",
"🔥 Bana karşı en samimi duygun nedir?",
"🔥 Benimle ilgili seni en çok etkileyen detay nedir?",
"🔥 Aramızdaki bağı sonsuza kadar korumak ister misin?",
"🔥 Bana dair unutamadığın bir söz var mı?",
"🔥 Beni neden hayatında görmek istiyorsun?",
"🔥 Bana karşı hislerini tek cümleyle anlatabilir misin?",
"🔥 Benim hangi hareketim seni gülümsetiyor?",
"🔥 Aramızdaki en güzel tesadüf nedir?",
"🔥 Bana dair en sevdiğin alışkanlık nedir?",
"🔥 Beni özlediğinde ne hissediyorsun?",
"🔥 Bana karşı hissettiğin sevgiyi nasıl tanımlarsın?",
"🔥 Benim hangi özelliğime hayransın?",
"🔥 Aramızdaki bağı güçlü yapan şey nedir?",
"🔥 Bana dair seni en çok heyecanlandıran şey nedir?",
"🔥 Beni düşündüğünde zaman duruyor gibi oluyor mu?",
"🔥 Bana karşı hislerinin gelecekte değişeceğini düşünüyor musun?",
"🔥 Benim hangi davranışım seni bana daha çok yaklaştırıyor?",
"🔥 Aramızdaki ilişkiyi bir kelimeyle anlatsan ne derdin?",
"🔥 Bana dair en çok neyi merak etmeye devam ediyorsun?",
"🔥 Beni ilk kez farklı gördüğün an hangisiydi?",
"🔥 Bana karşı hissettiğin en güzel duygu nedir?",
"🔥 Benim hangi sözüm sende iz bıraktı?",
"🔥 Aramızdaki en değerli an hangisi?",
"🔥 Bana dair unutamadığın bir bakış var mı?",
"🔥 Beni düşündüğünde aklına gelen ilk görüntü nedir?",
"🔥 Bana karşı hislerini anlatan bir film seçsen hangisi olurdu?",
"🔥 Benim hangi özelliğim seni güvende hissettiriyor?",
"🔥 Aramızdaki çekimin en güçlü yanı nedir?",
"🔥 Bana dair en sevdiğin hatıra nedir?",
"🔥 Beni ilk özlediğinde ne yaptın?",
"🔥 Bana karşı hislerini neden özel buluyorsun?",
"🔥 Benim hangi davranışım seni mutlu ediyor?",
"🔥 Aramızdaki bağı tarif eden bir şarkı var mı?",
"🔥 Bana dair kalbinde sakladığın düşünce nedir?",
"🔥 Beni neden unutulmaz buluyorsun?",
"🔥 Bana karşı hissettiğin en yoğun sevgi anı hangisiydi?",
"🔥 Benim hangi özelliğim seni şaşırtmaya devam ediyor?",
"🔥 Aramızdaki ilişkinin en güzel yanı nedir?",
"🔥 Bana dair ilk dikkatini çeken şey neydi?",
"🔥 Beni düşündüğünde neden gülümsüyorsun?",
"🔥 Bana karşı hislerini anlatan bir cümle kurabilir misin?",
"🔥 Benim hangi alışkanlığımı seviyorsun?",
"🔥 Aramızdaki en güçlü duygu nedir?",
"🔥 Bana dair seni etkileyen küçük detay hangisi?",
"🔥 Beni hayatında özel yapan şey nedir?",
"🔥 Bana karşı hissettiğin en dürüst duygu nedir?",
"🔥 Benim hangi hareketim seni etkiliyor?",
"🔥 Aramızdaki çekimin başlangıcı neydi?",
"🔥 Bana dair en sevdiğin an hangisidir?",
"🔥 Beni özlediğinde ilk kimi aramak istersin?",
"🔥 Bana karşı hislerini sakladığın oldu mu?",
"🔥 Benim hangi özelliğim seni bana çekiyor?",
"🔥 Aramızdaki bağı anlatan bir renk seçsen hangisi olurdu?",
"🔥 Bana dair en sevdiğin sürpriz nedir?",
"🔥 Beni düşündüğünde aklına gelen ilk his nedir?",
"🔥 Bana karşı hissettiğin sevgiyi nasıl gösterirsin?",
"🔥 Aramızdaki en unutulmaz duygu hangisiydi?",
"🔥 Bana söylemek istediğin en cesur söz ne olurdu?",
    "🔥 Bana karşı ilk kıskançlığını hatırlıyor musun?",
"🔥 Bende seni en çok etkileyen gülüş mü bakış mı?",
"🔥 Bana karşı hissettiğin en yoğun an hangisiydi?",
"🔥 Beni düşündüğünde kalbin nasıl tepki veriyor?",
"🔥 Aramızdaki en güçlü çekim sence nedir?",
"🔥 Bana söylemek isteyip uzun süre sakladığın şey neydi?",
"🔥 Benim hangi davranışım seni bana daha çok bağlıyor?",
"🔥 Bana ilk kez farklı baktığını ne zaman fark ettin?",
"🔥 Aramızdaki en unutulmaz yakınlık hangisiydi?",
"🔥 Beni gördüğünde ilk dikkat ettiğin şey ne oluyor?",
"🔥 Bana karşı hislerini tek kelimeyle anlatabilir misin?",
"🔥 Bende seni en çok etkileyen detay nedir?",
"🔥 Bana dair en çok neyi merak ediyorsun?",
"🔥 Beni özlediğinde ilk yapmak istediğin şey nedir?",
"🔥 Aramızdaki bağı özel yapan şey nedir?",
"🔥 Bana karşı en dürüst itirafın ne olurdu?",
"🔥 Beni ilk gördüğünde beğendiğin şey neydi?",
"🔥 Bana dair en sevdiğin hayal nedir?",
"🔥 Aramızdaki enerjiyi bir renkle anlatsan hangi renk olurdu?",
"🔥 Benim hangi sözüm sende iz bıraktı?",
"🔥 Bana karşı hissettiğin en yoğun duygu hangisi?",
"🔥 Beni neden özel buluyorsun?",
"🔥 Aramızdaki çekimi nasıl tarif edersin?",
"🔥 Bana karşı sakladığın bir düşünce var mı?",
"🔥 Benim hangi özelliğim seni en çok etkiliyor?",
"🔥 Bana baktığında aklından geçen ilk şey nedir?",
"🔥 Beni ilk özlediğin günü hatırlıyor musun?",
"🔥 Aramızdaki en güzel tesadüf nedir?",
"🔥 Bana dair unutamadığın ilk izlenim nedir?",
"🔥 Benimle ilgili en çok neyi seviyorsun?",
"🔥 Bana karşı hislerini bir şarkıyla anlatsan hangi şarkı olurdu?",
"🔥 Beni düşündüğünde neden gülümsüyorsun?",
"🔥 Aramızdaki bağı üç kelimeyle anlatabilir misin?",
"🔥 Bana karşı hissettiğin en cesur düşünce nedir?",
"🔥 Benim hangi hareketim seni etkiliyor?",
"🔥 Bana dair en sevdiğin detay hangisi?",
"🔥 Beni gördüğünde zaman yavaşlıyor mu?",
"🔥 Aramızdaki en güçlü duygu nedir?",
"🔥 Bana karşı ilk heyecanını nasıl anlatırsın?",
"🔥 Benim hangi özelliğime hayransın?",
"🔥 Bana söylemek isteyip ertelediğin şey nedir?",
"🔥 Beni düşündüğünde en çok neyi hatırlıyorsun?",
"🔥 Aramızdaki ilk kıvılcım ne zaman oluştu?",
"🔥 Bana dair en güzel anın hangisi?",
"🔥 Benimle ilgili seni en çok şaşırtan şey nedir?",
"🔥 Bana karşı hissettiğin sevgiyi nasıl tarif edersin?",
"🔥 Beni özlediğinde hangi an aklına geliyor?",
"🔥 Aramızdaki en unutulmaz konuşma hangisiydi?",
"🔥 Bana dair ilk dikkatini çeken şey nedir?",
"🔥 Benim hangi davranışım kalbini yumuşatıyor?",
"🔥 Bana karşı hislerini bir cümleyle özetler misin?",
"🔥 Beni ilk gördüğünde hissettiğin şey neydi?",
"🔥 Aramızdaki ilişkiyi farklı yapan şey nedir?",
"🔥 Bana dair en sevdiğin hatıra nedir?",
"🔥 Benim hangi özelliğim seni güvende hissettiriyor?",
"🔥 Bana karşı en güçlü hissettiğin an hangisiydi?",
"🔥 Beni neden hayatında istiyorsun?",
"🔥 Aramızdaki bağı ne kadar güçlü görüyorsun?",
"🔥 Bana dair seni en çok etkileyen an hangisi?",
"🔥 Benimle ilgili aklından çıkmayan şey nedir?",
"🔥 Bana karşı hislerini anlatan bir film seçsen hangisi olurdu?",
"🔥 Beni düşündüğünde hangi duygu ağır basıyor?",
"🔥 Aramızdaki en tatlı detay nedir?",
"🔥 Bana söylemek istediğin romantik sır nedir?",
"🔥 Benim hangi bakışım aklında kaldı?",
"🔥 Bana dair en sevdiğin alışkanlık nedir?",
"🔥 Beni ilk kez özlediğini nasıl anladın?",
"🔥 Aramızdaki bağın en güzel yanı nedir?",
"🔥 Bana karşı hislerini anlatan bir renk var mı?",
"🔥 Benim hangi davranışım seni mutlu ediyor?",
"🔥 Bana dair en sevdiğin sürpriz nedir?",
"🔥 Beni düşündüğünde kalbin ne söylüyor?",
"🔥 Aramızdaki ilişkiyi bir kelimeyle anlatsan ne derdin?",
"🔥 Bana karşı hissettiğin heyecan hâlâ devam ediyor mu?",
"🔥 Benim hangi özelliğim seni kendine çekiyor?",
"🔥 Bana dair unutamadığın söz nedir?",
"🔥 Beni gördüğünde neden mutlu oluyorsun?",
"🔥 Aramızdaki en güzel anı hangisi?",
"🔥 Bana karşı en samimi duygun nedir?",
"🔥 Benimle ilgili seni en çok etkileyen detay hangisi?",
"🔥 Bana dair ilk fark ettiğin şey nedir?",
"🔥 Beni düşündüğünde aklına gelen ilk görüntü nedir?",
"🔥 Aramızdaki bağı özel yapan duygu nedir?",
"🔥 Bana karşı hislerini neden değerli buluyorsun?",
"🔥 Benim hangi özelliğim seni bana bağlıyor?",
"🔥 Bana dair en sevdiğin fotoğraf hangisi?",
"🔥 Beni özlediğinde ne hissediyorsun?",
"🔥 Aramızdaki çekim ilk ne zaman başladı?",
"🔥 Bana karşı hislerini anlatan bir cümle kurar mısın?",
"🔥 Benimle ilgili seni en çok etkileyen an hangisi?",
"🔥 Bana dair sakladığın güzel düşünce nedir?",
"🔥 Beni neden farklı görüyorsun?",
"🔥 Aramızdaki ilişkinin en güzel tarafı nedir?",
"🔥 Bana karşı hissettiğin en yoğun sevgi anı hangisiydi?",
"🔥 Benim hangi davranışım seni bana daha çok yaklaştırıyor?",
"🔥 Bana dair kalbinde sakladığın şey nedir?",
"🔥 Aramızdaki bağı gelecekte nasıl görüyorsun?",
"🔥 Bana söylemek istediğin son cesur cümle ne olurdu?",
"🔥 Bende seni en çok etkileyen şey nedir?",
"🔥 Bana ilk ne zaman farklı hissettin?",
"🔥 Bende en çekici bulduğun özellik nedir?",
"🔥 Bana söylemek isteyip söyleyemediğin bir şey var mı?",
"🔥 Aramızdaki en özel çekim nedir?",
"🔥 Bana uzun uzun baktığında ne düşünüyorsun?",
"🔥 Beni en çok hangi halimle seviyorsun?",
"🔥 Bana itiraf etmek istediğin tatlı bir şey var mı?",
"🔥 Beni en çok ne zaman özlüyorsun?",
"🔥 Aramızdaki enerjiyi nasıl tarif edersin?",
"🔥 Bende unutamadığın detay nedir?",
"🔥 Bana karşı en yoğun hissettiğin an hangisiydi?",
"🔥 Beni ilk gördüğünde aklından ne geçti?",
"🔥 Bana söylemek istediğin cesur bir cümle ne olurdu?",
"🔥 Benimle ilgili en özel düşüncen nedir?",
"🔥 Beni kıskandığın bir an oldu mu?",
"🔥 Bana karşı ilk heyecanını hatırlıyor musun?",
"🔥 Beni düşündüğünde yüzünde nasıl bir ifade oluşuyor?",
"🔥 Aramızdaki en çekici şey nedir?",
"🔥 Benim hangi davranışım seni etkiliyor?",
"🔥 Bana söylemekten çekindiğin bir iltifat var mı?",
"🔥 Beni gördüğünde kalbin hızlanıyor mu?",
"🔥 Bende seni en çok şaşırtan şey neydi?",
"🔥 Bana karşı hissettiğin en güçlü duygu nedir?",
"🔥 Aramızdaki ilk elektrik ne zaman oluştu?",
"🔥 Benimle ilgili en çok neyi merak ediyorsun?",
"🔥 Bana baktığında geleceği hayal ediyor musun?",
"🔥 Beni özlediğinde ilk ne yapmak istersin?",
"🔥 Bende seni kendine çeken özellik nedir?",
"🔥 Bana karşı en unutamadığın his nedir?",
"🔥 Benim hangi bakışım aklında kaldı?",
"🔥 Aramızdaki bağın en güçlü tarafı nedir?",
"🔥 Bana söylemek istediğin romantik bir sır var mı?",
"🔥 Benim yanımda en çok hangi duyguyu hissediyorsun?",
"🔥 Beni ilk kez farklı gördüğün an hangisiydi?",
"🔥 Bende seni etkileyen küçük bir detay nedir?",
"🔥 Bana dair aklından çıkmayan şey nedir?",
"🔥 Beni en çok hangi özelliğimle hatırlarsın?",
"🔥 Aramızdaki en unutulmaz an hangisiydi?",
"🔥 Bana karşı hissettiğin heyecanı nasıl anlatırsın?",
"🔥 Beni gördüğünde ilk dikkat ettiğin şey nedir?",
"🔥 Bana dair en tatlı itirafın ne olurdu?",
"🔥 Benimle ilgili hayal kuruyor musun?",
"🔥 Bana karşı sakladığın bir düşünce var mı?",
"🔥 Aramızdaki çekimi bir kelimeyle anlatsan ne derdin?",
"🔥 Bende seni etkileyen ilk şey neydi?",
"🔥 Bana baktığında ne hissettiğini hiç söyledin mi?",
"🔥 Benimle ilgili seni en çok etkileyen an hangisi?",
"🔥 Bana karşı ilk hissettiğin duygu neydi?",
"🔥 Beni neden özel buluyorsun?",
"🔥 Benim hangi davranışım seni heyecanlandırıyor?",
"🔥 Bana karşı hissettiğin en yoğun an hangisiydi?",
"🔥 Aramızdaki bağı nasıl tarif edersin?",
"🔥 Beni düşündüğünde aklına gelen ilk şey nedir?",
"🔥 Bana dair unutamadığın detay nedir?",
"🔥 Benim hangi sözüm sende iz bıraktı?",
"🔥 Beni özlediğinde ne hissediyorsun?",
"🔥 Bana dair en sevdiğin anı hangisi?",
"🔥 Beni gördüğünde en çok ne hoşuna gidiyor?",
"🔥 Aramızdaki en güzel tesadüf nedir?",
"🔥 Bana söylemek istediğin ama ertelediğin şey nedir?",
"🔥 Benimle ilgili seni en çok etkileyen özellik hangisi?",
"🔥 Beni farklı yapan şey nedir?",
"🔥 Bana karşı en dürüst düşüncen nedir?",
"🔥 Aramızdaki ilk yakınlığı hatırlıyor musun?",
"🔥 Bende seni etkileyen bir bakış var mı?",
"🔥 Bana dair aklında kalan ilk izlenim nedir?",
"🔥 Benimle ilgili en sevdiğin detay hangisi?",
"🔥 Beni düşündüğünde hangi duygu baskın geliyor?",
"🔥 Bana karşı en cesur düşüncen nedir?",
"🔥 Aramızdaki en güçlü çekim nedir?",
"🔥 Beni ilk gördüğün anı nasıl anlatırsın?",
"🔥 Bana dair en çok neyi seviyorsun?",
"🔥 Beni özlediğinde ne yaparsın?",
"🔥 Aramızdaki bağı özel yapan şey nedir?",
"🔥 Bana karşı hislerini tek cümleyle anlatır mısın?",
"🔥 Benim hangi hareketim seni etkiliyor?",
"🔥 Bende seni en çok mutlu eden şey nedir?",
"🔥 Bana dair hayalini kursan ne olurdu?",
"🔥 Beni düşündüğünde neden gülümsüyorsun?",
"🔥 Bana karşı en güzel hissettiğin an hangisiydi?",
"🔥 Aramızdaki ilişkiyi nasıl tanımlarsın?",
"🔥 Bende seni etkileyen ses tonu mu bakış mı?",
"🔥 Bana dair unutamadığın söz nedir?",
"🔥 Beni ilk özlediğin an hangisiydi?",
"🔥 Aramızdaki en tatlı detay nedir?",
"🔥 Bana karşı hislerini anlatan bir şarkı var mı?",
"🔥 Benimle ilgili en sevdiğin alışkanlık nedir?",
"🔥 Beni neden hayatında görmek istiyorsun?",
"🔥 Aramızdaki çekimi neye benzetirsin?",
"🔥 Bana dair seni en çok heyecanlandıran şey nedir?",
"🔥 Benim hangi özelliğim seni bana bağlıyor?",
"🔥 Beni düşündüğünde kalbin ne söylüyor?",
"🔥 Bana karşı hissettiğin en samimi duygu nedir?",
"🔥 Aramızdaki en özel anı hangisi?",
"🔥 Bana söylemek istediğin son cesur cümle ne olurdu?",

    "🔥 Bende seni en çok etkileyen şey ne?",
    "🔥 Bana ilk ne zaman farklı hissettin?",
    "🔥 Bende en çekici bulduğun özellik ne?",
    "🔥 Bana söylemek isteyip çekindiğin şey ne?",
    "🔥 Aramızdaki en özel çekim ne?",
    "🔥 Bana uzun uzun baktığında ne düşünüyorsun?",
    "🔥 Beni en çok hangi halimle seviyorsun?",
    "🔥 Bana itiraf etmek istediğin tatlı bir şey var mı?",
    "🔥 Beni en çok ne zaman özlüyorsun?",
    "🔥 Aramızdaki enerjiyi nasıl tarif edersin?",
    "🔥 Bende unutamadığın detay ne?",
    "🔥 Bana karşı en yoğun hissettiğin an hangisiydi?",
    "🔥 Beni ilk gördüğünde aklından ne geçti?",
    "🔥 Bana söylemek istediğin cesur bir cümle ne?",
    "🔥 Benimle ilgili en özel düşüncen ne?",
  ]
};


let lastQuestion = "";

function randomItem(arr){
  return arr[Math.floor(Math.random() * arr.length)];
}

function generateQuestion(){
  const category = document.getElementById("category").value;
  const list = data[category];

  if(!list || list.length === 0){
    alert("Bu kategoride soru yok");
    return;
  }

  let question = randomItem(list);

  if(question === lastQuestion && list.length > 1){
    question = randomItem(list);
  }

  lastQuestion = question;

  const questionBox = document.getElementById("question");
  const card = document.querySelector(".question-card");

if(card){
    card.classList.add("change");

    setTimeout(() => {
        questionBox.innerText = question;
        card.classList.remove("change");
    }, 300);
}
}
  
  



function copyQuestion(){
  const text = document.getElementById("question").innerText;
  navigator.clipboard.writeText(text);
  alert("📋 Soru kopyalandı!");
}

function shareWhatsApp(){
  const text = document.getElementById("question").innerText;
  window.open(`https://wa.me/?text=${encodeURIComponent(text)}`, "_blank");
}

function randomCategory(){
  const categories = ["romantik", "eglenceli", "derin", "cesur"];
  const random = randomItem(categories);

  document.getElementById("category").value = random;
  generateQuestion();
}

window.addEventListener("load", generateQuestion);
function toggleSideMenu(){
  const menu = document.getElementById("sideMenu");
  menu.classList.toggle("open");
}
let startX = 0;
let historyQuestions = [];

window.addEventListener("load", () => {

  const card = document.querySelector(".question-card");
  const questionBox = document.getElementById("question");

  if(!card || !questionBox) return;

  card.addEventListener("touchstart", (e) => {
    startX = e.touches[0].clientX;
  });

  card.addEventListener("touchend", (e) => {

    const endX = e.changedTouches[0].clientX;
    const diff = endX - startX;

    // Sağa kaydır = Yeni soru
    if(diff > 70){
      historyQuestions.push(questionBox.innerText);
      generateQuestion();
    }

    // Sola kaydır = Eski soru
    if(diff < -70 && historyQuestions.length > 0){
      questionBox.innerText = historyQuestions.pop();
    }

  });

});

  

  
